{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "velero-notifications.fullname" . }}
  labels:
    {{- include "velero-notifications.labels" . | nindent 4 }}
rules:
- apiGroups: ["velero.io"]
  resources: ["backups"]
  verbs:     ["get", "list", "watch"]
- apiGroups: ["velero.io"]
  resources: ["restores"]
  verbs:     ["get", "list", "watch"]
{{- end -}}
