apiVersion: v1
kind: Secret
metadata:
  name: {{ include "velero-notifications.fullname" . }}-secrets
type: Opaque
stringData:
  SLACK_WEBHOOK: {{ .Values.configuration.slack.webhook | quote }}
  SLACK_CHANNEL: {{ .Values.configuration.slack.channel | quote }}

  EMAIL_SMTP_HOST: {{ .Values.configuration.email.smtp.host | quote }}
  EMAIL_SMTP_PORT: {{ .Values.configuration.email.smtp.port | quote }}
  EMAIL_SMTP_USERNAME: {{ .Values.configuration.email.smtp.username | quote }}
  EMAIL_SMTP_PASSWORD: {{ .Values.configuration.email.smtp.password | quote }}

  WEBHOOK_URL: {{ .Values.configuration.webhook.url | quote }}
