# We publish every merged commit in the form of an image
# named velero-notifications:<branch>-<short tag>
name: Push image of latest main
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'charts/**'
  workflow_dispatch:

jobs:
  tag-scan-and-push-final-image:
    name: "Build, scan, and publish tagged image"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: weave-ghcr-bot
          password: ${{ secrets.GHCR_BOT_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Find current tag version
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        id: tags

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          platforms: linux/arm64, linux/amd64, linux/arm/v7, linux/arm/v6
          push: true
          tags: |
            ghcr.io/${{ GITHUB.REPOSITORY }}:main-${{ steps.tags.outputs.sha_short }}
