name: Tag repo
on:
  push:
    tags:
      - "*"
jobs:
  tag-scan-and-push-final-image:
    name: "Build and publish tagged image"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Find current tag version
        run: echo "::set-output name=version::${GITHUB_REF#refs/tags/}"
        id: tags

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          platforms: linux/arm64, linux/amd64, linux/arm/v7, linux/arm/v6
          push: true
          tags: |
            ghcr.io/${{ GITHUB.REPOSITORY }}:${{ steps.tags.outputs.version }}
